"""Store — protocol for chapter translation storage operations."""

from __future__ import annotations

from typing import Protocol


class Store(Protocol):
    """Minimal storage interface required by the translate pipeline."""

    async def get_glossary(self, project_id: int) -> dict[str, str]: ...
    async def glossary_search(self, project_id: int, query: str) -> list[dict]: ...
    async def save_chapter_brief(self, project_id: int, chapter: float, brief: dict) -> None: ...
    async def get_recent_chapter_briefs(self, project_id: int, before_chapter: float, limit: int = 3) -> list[dict]: ...
    async def search_briefs(self, project_id: int, queries: list[str], limit: int = 10, *, before_chapter: float | None = None) -> list[str]: ...
    async def search_context(self, project_id: int, queries: list[str], scope: str = "all", limit: int = 12) -> list[str]: ...
    async def save_translations(self, project_id: int, chapter: float, records: list[dict]) -> None: ...
