"""Ports — protocol definitions only. No data types, no logic.

Adapters implement these protocols.
Data types live in types.py.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Protocol, runtime_checkable

import numpy as np

if TYPE_CHECKING:
    from .domain.bubble import Bubble
    from .domain.project import ChapterVariant, DiscoveredChapter, SourceInfo


@runtime_checkable
class ChapterSource(Protocol):
    """Provides page images for a single chapter."""

    async def fetch(self) -> None: ...
    def page_count(self) -> int: ...
    def load_page(self, index: int) -> np.ndarray: ...


@runtime_checkable
class Connector(Protocol):
    """Discovers manga from a source site. Site-specific logic only."""

    @property
    def site_name(self) -> str: ...
    def accepts(self, url: str) -> bool: ...
    def is_authenticated(self) -> bool: ...
    async def authenticate(self) -> None:
        """Obtain credentials. How depends on platform (CLI: browser, Server: API)."""
        ...
    async def discover(self, url: str) -> SourceInfo: ...
    async def get_page_urls(self, chapter: DiscoveredChapter, variant: ChapterVariant | None = None) -> list[str]: ...
    def http_headers(self) -> dict[str, str]: ...


@runtime_checkable
class Store(Protocol):
    """Persistent storage for projects, translations, knowledge."""

    # Projects
    async def get_project(self, project_id: int) -> dict | None: ...
    async def get_project_by_title(self, title: str) -> dict | None: ...
    async def get_project_by_url(self, source_url: str) -> dict | None: ...

    # Chapters
    async def add_chapter(self, project_id: int, idx: float, **kw) -> int: ...
    async def set_chapter_status(self, project_id: int, idx: float, status: str) -> None: ...
    async def get_chapter_status(self, project_id: int, idx: float) -> str | None: ...
    async def get_chapter_retry_count(self, project_id: int, idx: float) -> int: ...
    async def increment_retry_count(self, project_id: int, idx: float) -> None: ...
    async def delete_chapter_data(self, project_id: int, idx: float) -> None: ...

    # Translations
    async def save_translations(self, project_id: int, chapter: float, bubbles: list[Bubble]) -> None: ...
    async def get_chapter_translations(self, project_id: int, chapter: float) -> list[dict]: ...

    # Knowledge
    async def get_knowledge(self, project_id: int, before_chapter: float) -> str | None: ...
    async def save_knowledge(self, project_id: int, chapter: float, snapshot: str) -> None: ...

    # Glossary
    async def get_glossary(self, project_id: int) -> dict[str, str]: ...
    async def glossary_search(self, project_id: int, query: str) -> list[dict]: ...
    async def glossary_upsert(self, project_id: int, source_term: str, target_term: str, notes: str | None) -> None: ...

    # Notes + context
    async def add_note(self, project_id: int, chapter: float, note_type: str, content: str) -> None: ...
    async def search_context(self, project_id: int, queries: list[str], scope: str, limit: int) -> list[str]: ...
    async def get_chapter_pairs(self, project_id: int, chapter: float) -> list[tuple[str, str]]: ...

    # Review/edit
    async def update_bubble(self, project_id: int, chapter: float, page: int, idx: int, text: str) -> None: ...

    # List
    async def list_projects(self) -> list[dict]: ...
