/// <reference path="./types/lens-proto.d.ts" />

export { BrowserSdkError } from './errors'
export type { BrowserSdkErrorCode } from './errors'
export { DomOverlayTarget } from './adapters/DomOverlayTarget'
export type { DomOverlayTargetOptions } from './adapters/DomOverlayTarget'
export { DomPageSource } from './adapters/DomPageSource'
export type { DomPageSourceOptions } from './adapters/DomPageSource'
export { ModelRepository } from './adapters/ModelRepository'
export { ModelLoader } from './models/ModelLoader'
export { OrtRuntime } from './models/OrtRuntime'
export type { OrtRuntimeOptions } from './models/OrtRuntime'
export { OrtSessionPool } from './models/OrtSessionPool'
export type { OrtProvider, OrtSessionHandle } from './models/OrtSessionPool'
export type { ModelAssetCache, ModelDescriptor, ModelManifest, ModelRepositoryOptions } from './adapters/modelTypes'
export { huggingFaceManifestUrl, huggingFaceResolveUrl } from './adapters/huggingFace'
export type { HuggingFaceModelRepositoryOptions } from './adapters/huggingFace'
export { detectBrowserCapabilities } from './adapters/browserCapabilities'
export type { BrowserCapabilities, BrowserModelHint } from './adapters/browserCapabilities'
export type { AddressRule, CharacterProfile, GlossaryEntry, TranslationContext } from './domain/context'
export { MangaTextRegionDetector } from './detectors/manga/MangaTextRegionDetector'
export type { ComicDetrDetectorOptions } from './detectors/manga/MangaTextRegionDetector'
export type { TextRegionDetector } from './detectors/textRegions'
export { LensTextRecognizer } from './recognizers/lens/LensTextRecognizer'
export type { LensTextRecognizerOptions } from './recognizers/lens/LensTextRecognizer'
export type { TextRecognizer, TextRecognitionOptions } from './recognizers/text'
export type { PageSource } from './domain/source'
export { DeepLTranslateWeb } from './translators/deepl-web/DeepLTranslateWeb'
export type { DeepLTranslateWebOptions } from './translators/deepl-web/DeepLTranslateWeb'
export { GoogleTranslateWeb } from './translators/google-web/GoogleTranslateWeb'
export type { GoogleTranslateWebOptions } from './translators/google-web/GoogleTranslateWeb'
export type { Translator, TranslateUnitsArgs } from './translators/translator'
export type { TranslationPostEditor } from './translators/postEditor'
export { DEFAULT_STAGE_CONCURRENCY, TranslationEngine } from './flow/TranslationEngine'
export type { SegmentDisplayOptions, TranslateSegmentOptions, TranslationEngineOptions } from './flow/TranslationEngine'
export { SegmentTranslationRun } from './flow/SegmentTranslationRun'

export type { StageConcurrencyPolicy, StageRetryOptions, StageSchedulerOptions } from './flow/StageScheduler'
export type { ImageInput } from './image/input'
export type { CanvasPage } from './domain/canvas'
export { CapabilityMachine } from './runtime/CapabilityMachine'
export type { Capability, CapabilityProgress, CapabilityState, CapabilityStatus, ReadyOptions, StatusListener, StatusSnapshot, Unsubscribe } from './domain/capability'
export type { BBox, Point, Polygon } from './domain/geometry'
export type { ImagePixels } from './domain/image'
export type { FontHint, TextPlacement, TextRole } from './domain/planning'
export type { PageTextRegions, TextRegion, TextRegionKind } from './domain/regions'
export type { RecognizedTextPage, TextBlock, TextDirection, TextLine, TextUnit, TextWord } from './domain/text'
export type { RenderedPage, RenderPhase, TranslatedUnit, TranslationKind, TranslationUnit } from './domain/translation'
export type { LayoutPlan, SegmentRequest, SegmentScript, TranslationVersion } from './domain/segment'
export { createOverlayElement, attachOverlay } from './render/overlay'
export type { OverlayOptions } from './render/overlay'
export { createDebugLayer } from './render/debugLayer'
export type { OverlayDebugOptions } from './render/debugLayer'
export type { ErasePlan, EraseShape, EraseStrategy, BuildErasePlanOptions } from './render/erasePlan'
export { buildErasePlan } from './render/erasePlan'
export { createEraseLayer } from './render/eraseLayer'
export { createTextLayer } from './render/textLayer'
export { buildTextStyle } from './render/textStyle'
export type { TextStrokePlan, TextStylePlan } from './render/textStyle'
export { MANGA_FONT_FAMILY, MANGA_FONT_PROFILE, ensureMangaFontLoaded } from './render/font'
export type { FontMetrics, FontProfile } from './render/font'

// ── Production run API ──

export { TranslationRuntime } from './runtime/TranslationRuntime'
export { TranslationRun } from './runtime/TranslationRun'
export { TranslationStageSession } from './runtime/TranslationStageSession'
export type { TranslationStageSessionDeps, RuntimeStageRequest } from './runtime/TranslationStageSession'
export { StageExecutor } from './runtime/StageExecutor'
export { PreparedChapterSource } from './runtime/PreparedChapterSource'
export type { PipelineConcurrency } from './runtime/StageExecutor'
export { MainThreadVisionRuntime } from './vision/MainThreadVisionRuntime'
export { ComlinkVisionRuntime } from './vision/ComlinkVisionRuntime'
export type { VisionRuntime, PreparationSession } from './vision/VisionRuntime'
export type { PageDocumentSource, PageAsset, PageSize, Rect } from './domain/source'
export type { PreparedPageHandle, PageProjection } from './domain/prepared'
export type { PreparedChapter, PreparedPage, PreparedPageAsset, SourcePageMapping } from './domain/preparedChapter'
export type { PrepareProfile, PrepareRequest, PrepareStrategy, SourcePresentation, SeamPolicy, SeamDecisionPolicy, PrepareMemoryPolicy, PrepareArtifactSink } from './domain/prepare'
export { CONTINUOUS_STRIP_PREPARE_PROFILE, DEFAULT_PREPARE_PROFILE } from './domain/prepare'
export { prepareChapter } from './stages/prepare/prepareChapter'
export type { PageOverlay } from './domain/overlay'
export type { PageTranslationStatus, TranslationProgress, TranslationRequest, TranslationRunEvent, PreparationStrategy } from './domain/run'
