/// <reference path="./types/lens-proto.d.ts" />

export { detectBrowserCapabilities } from './adapters/browserCapabilities'
export type { BrowserCapabilities, BrowserModelHint } from './adapters/browserCapabilities'
export { LensTextRecognizer } from './recognizers/lens/LensTextRecognizer'
export { DeepLTranslateWeb } from './translators/deepl-web/DeepLTranslateWeb'
export { GoogleTranslateWeb } from './translators/google-web/GoogleTranslateWeb'
export { MangaTextRegionDetector } from './detectors/manga/MangaTextRegionDetector'
export { ModelRepository } from './adapters/ModelRepository'
export { OrtRuntime } from './models/OrtRuntime'
export { OrtSessionPool } from './models/OrtSessionPool'
export { attachOverlay } from './render/overlay'
export { ensureMangaFontLoaded } from './render/font'
export { TranslationRuntime } from './runtime/TranslationRuntime'
export { TranslationStageSession } from './runtime/TranslationStageSession'
export { MainThreadVisionRuntime } from './vision/MainThreadVisionRuntime'
export { ComlinkVisionRuntime } from './vision/ComlinkVisionRuntime'
export type { PageOverlay } from './domain/overlay'
export type { PageAsset } from './domain/source'
export type { PreparedPageHandle } from './domain/prepared'
export type { PreparedTextResult, PreparedTranslationResult } from './pipeline/translatePreparedPage'
export type { TranslationRunEvent } from './domain/run'

// ── Reader translation controller (public API) ──
export { ReaderTranslation, type ReaderModelState, type ReaderTranslationChapter, type ReaderTranslationState } from './reader/translation'
