name = "typoon-typeset"
account_id = "818e551312970df676abe1a0e61819c7"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[placement]
mode = "smart"

[durable_objects]
bindings = [
  { name = "TYPESET_DO", class_name = "TypesetRender" }
]

[[migrations]]
tag = "v1"
new_classes = ["TypesetRender"]

[[r2_buckets]]
binding     = "R2"
bucket_name = "typoon-work"

[vars]
FONT_KEY = "fonts/SamaritanTall-TB.ttf"
