export { BrowserSdkError } from './errors'
export type { BrowserSdkErrorCode } from './errors'
export { DomOverlayTarget } from './adapters/DomOverlayTarget'
export type { DomOverlayTargetOptions } from './adapters/DomOverlayTarget'
export { DomPageSource } from './adapters/DomPageSource'
export type { DomPageSourceOptions } from './adapters/DomPageSource'
export { ModelRepository } from './adapters/ModelRepository'
export { BrowserModelCache } from './adapters/BrowserModelCache'
export { ModelAsset } from './adapters/ModelAsset'
export type { ModelAssetCache, ModelDescriptor, ModelManifest, ModelRepositoryOptions, StoredModel } from './adapters/modelTypes'
export type { ContextBuilder, AddressRule, CharacterProfile, ContextRequest, GlossaryEntry, TranslationContext } from './context/ContextBuilder'
export { MangaTextRegionDetector } from './detectors/manga/MangaTextRegionDetector'
export type { ComicDetrDetectorOptions } from './detectors/manga/MangaTextRegionDetector'
export type { TextRegionDetector } from './detectors/textRegions'
export { LensTextRecognizer } from './recognizers/lens/LensTextRecognizer'
export type { LensTextRecognizerOptions } from './recognizers/lens/LensTextRecognizer'
export type { TextRecognizer, TextRecognitionOptions } from './recognizers/text'
export type { PageSource } from './domain/source'
export { GoogleTranslateWeb } from './translators/google-web/GoogleTranslateWeb'
export type { GoogleTranslateWebOptions } from './translators/google-web/GoogleTranslateWeb'
export type { Translator } from './translators/translator'
export { DEFAULT_STAGE_CONCURRENCY, TranslationEngine } from './flow/TranslationEngine'
export type { TranslateSegmentOptions, TranslationEngineOptions } from './flow/TranslationEngine'
export { SegmentTranslationRun } from './flow/SegmentTranslationRun'
export type { SegmentTranslationRunOptions } from './flow/SegmentTranslationRun'
export type { DisplayPolicy } from './flow/PageDataflow'
export type { StageConcurrencyPolicy, StageRetryOptions, StageSchedulerOptions, StageSchedulerPolicy } from './flow/StageScheduler'
export type { SegmentEvent, SegmentEventListener, StageMetrics } from './flow/events'
export type { ImageInput } from './image/input'
export type { CanvasPage, CanvasWindow } from './domain/canvas'
export type { Capability, CapabilityProgress, CapabilityState, CapabilityStatus, ReadyOptions, StatusListener, StatusSnapshot, Unsubscribe } from './domain/capability'
export { isCapability } from './domain/capability'
export type { BBox, Point, Polygon } from './domain/geometry'
export type { ImagePixels } from './domain/image'
export type { FontHint, TextPlacement, TextRole } from './domain/planning'
export type { PageTextRegions, TextRegion, TextRegionKind } from './domain/regions'
export type { RecognizedTextPage, TextBlock, TextDirection, TextLine, TextUnit, TextWord } from './domain/text'
export type { RenderedPage, RenderPhase, TranslatedUnit, TranslationKind, TranslationUnit } from './domain/translation'
export { createOverlayElement, attachOverlay } from './render/overlay'
export type { OverlayOptions } from './render/overlay'
export { createDebugLayer } from './render/debugLayer'
export type { OverlayDebugOptions } from './render/debugLayer'
export type { ErasePlan, EraseShape, EraseStrategy, BuildErasePlanOptions } from './render/erasePlan'
export { buildErasePlan } from './render/erasePlan'
export { createEraseLayer } from './render/eraseLayer'
export { createTextLayer } from './render/textLayer'
export { buildTextStyle } from './render/textStyle'
export type { TextStrokePlan, TextStylePlan } from './render/textStyle'
export { MANGA_FONT_FAMILY, MANGA_FONT_PROFILE, ensureMangaFontLoaded } from './render/font'
export type { FontMetrics, FontProfile } from './render/font'
