// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEnabledCoinPackages = `-- name: ListEnabledCoinPackages :many
SELECT id, name, xu_amount, bonus_xu, price_vnd
FROM coin_packages
WHERE enabled = true
ORDER BY sort_order ASC, price_vnd ASC
`

type ListEnabledCoinPackagesRow struct {
	ID       pgtype.UUID
	Name     string
	XuAmount int32
	BonusXu  int32
	PriceVnd int32
}

func (q *Queries) ListEnabledCoinPackages(ctx context.Context, db DBTX) ([]ListEnabledCoinPackagesRow, error) {
	rows, err := db.Query(ctx, listEnabledCoinPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledCoinPackagesRow
	for rows.Next() {
		var i ListEnabledCoinPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.XuAmount,
			&i.BonusXu,
			&i.PriceVnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
