// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm.sql

package sqlc

import (
	"context"
)

const getProfilesForPurpose = `-- name: GetProfilesForPurpose :many
SELECT
  p.id, p.provider_id, p.model, p.protocol, p.endpoint_path, p.timeout_ms,
  pr.base_url, pr.api_key_ref
FROM llm_policies policy
CROSS JOIN LATERAL jsonb_array_elements_text(policy.profile_chain_json)
  WITH ORDINALITY AS chain(profile_id, ord)
JOIN llm_profiles p ON p.id = chain.profile_id
JOIN llm_providers pr ON pr.id = p.provider_id
WHERE policy.purpose = $1
  AND policy.enabled = true
  AND p.enabled = true
  AND pr.enabled = true
ORDER BY chain.ord
`

type GetProfilesForPurposeRow struct {
	ID           string
	ProviderID   string
	Model        string
	Protocol     string
	EndpointPath string
	TimeoutMs    int32
	BaseUrl      string
	ApiKeyRef    string
}

func (q *Queries) GetProfilesForPurpose(ctx context.Context, db DBTX, purpose string) ([]GetProfilesForPurposeRow, error) {
	rows, err := db.Query(ctx, getProfilesForPurpose, purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilesForPurposeRow
	for rows.Next() {
		var i GetProfilesForPurposeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.Protocol,
			&i.EndpointPath,
			&i.TimeoutMs,
			&i.BaseUrl,
			&i.ApiKeyRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
