// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TokenHash  string
	Origin     string
	UserAgent  *string
	IpHash     *string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type CoinPackage struct {
	ID        pgtype.UUID
	Name      string
	XuAmount  int32
	BonusXu   int32
	PriceVnd  int32
	Enabled   bool
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Flow struct {
	ID          pgtype.UUID
	Kind        string
	Status      string
	UserID      pgtype.UUID
	StateHash   *string
	ContextJson []byte
	ResultJson  []byte
	ExpiresAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type LlmAttempt struct {
	ID           pgtype.UUID
	Purpose      string
	ProviderID   *string
	ProfileID    *string
	Status       string
	LatencyMs    int32
	ErrorCode    *string
	InputTokens  *int32
	OutputTokens *int32
	TotalTokens  *int32
	CreatedAt    pgtype.Timestamptz
}

type LlmPolicy struct {
	Purpose          string
	ProfileChainJson []byte
	Enabled          bool
	UpdatedAt        pgtype.Timestamptz
}

type LlmProfile struct {
	ID           string
	ProviderID   string
	Name         string
	Model        string
	Protocol     string
	EndpointPath string
	ParamsJson   []byte
	TimeoutMs    int32
	Enabled      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type LlmProvider struct {
	ID        string
	Name      string
	Kind      string
	BaseUrl   string
	ApiKeyRef string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type OauthAccount struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Provider          string
	ProviderAccountID string
	Username          *string
	AvatarUrl         *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentOrder struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Provider          string
	ProviderOrderCode string
	CoinPackageID     pgtype.UUID
	AmountVnd         int32
	XuAmount          int32
	Status            string
	IdempotencyKey    *string
	CheckoutUrl       *string
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentWebhookEvent struct {
	ID                pgtype.UUID
	Provider          string
	ProviderOrderCode string
	PayloadHash       string
	PayloadJson       []byte
	SignatureValid    bool
	ProcessedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type TranslationEntitlement struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ContentKey string
	TargetLang string
	SessionID  pgtype.UUID
	GrantedAt  pgtype.Timestamptz
}

type TranslationHold struct {
	SessionID  pgtype.UUID
	UserID     pgtype.UUID
	AmountXu   int32
	State      string
	HeldAt     pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
}

type TranslationPriceRule struct {
	ID        pgtype.UUID
	Name      string
	Mode      string
	PriceXu   int32
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TranslationRefineCache struct {
	CacheKey     string
	TargetLang   string
	SourceHash   string
	DraftHash    string
	TargetText   string
	LlmProfileID *string
	CreatedAt    pgtype.Timestamptz
}

type TranslationRefineWindow struct {
	ID           pgtype.UUID
	SessionID    pgtype.UUID
	WindowIndex  int32
	RequestJson  []byte
	ResponseJson []byte
	Status       string
	LlmProfileID *string
	LatencyMs    *int32
	ErrorCode    *string
	CreatedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type TranslationSession struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ContentKey   string
	WorkID       *string
	SegmentID    *string
	SourceLang   *string
	TargetLang   string
	Mode         string
	State        string
	XuState      string
	PriceXu      int32
	PageCount    *int32
	UnitCount    *int32
	ErrorCode    *string
	ErrorMessage *string
	CreatedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	DisplayName *string
	AvatarUrl   *string
	IsAdmin     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WalletAccount struct {
	UserID      pgtype.UUID
	AvailableXu int32
	HeldXu      int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WalletLedger struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Kind                  string
	AvailableDeltaXu      int32
	HeldDeltaXu           int32
	BalanceAvailableAfter int32
	BalanceHeldAfter      int32
	ReferenceType         string
	ReferenceID           string
	Note                  *string
	CreatedByAdminID      pgtype.UUID
	CreatedAt             pgtype.Timestamptz
}
