// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCheckoutURL = `-- name: AttachCheckoutURL :exec
UPDATE payment_orders
SET checkout_url = $2, updated_at = now()
WHERE id = $1
`

type AttachCheckoutURLParams struct {
	ID          pgtype.UUID
	CheckoutUrl *string
}

func (q *Queries) AttachCheckoutURL(ctx context.Context, db DBTX, arg *AttachCheckoutURLParams) error {
	_, err := db.Exec(ctx, attachCheckoutURL, arg.ID, arg.CheckoutUrl)
	return err
}

const createPendingOrder = `-- name: CreatePendingOrder :exec
INSERT INTO payment_orders
  (id, user_id, provider, provider_order_code, coin_package_id, amount_vnd, xu_amount, status, checkout_url)
VALUES ($1, $2, 'payos', $3, $4, $5, $6, 'pending', $7)
`

type CreatePendingOrderParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	ProviderOrderCode string
	CoinPackageID     pgtype.UUID
	AmountVnd         int32
	XuAmount          int32
	CheckoutUrl       *string
}

func (q *Queries) CreatePendingOrder(ctx context.Context, db DBTX, arg *CreatePendingOrderParams) error {
	_, err := db.Exec(ctx, createPendingOrder,
		arg.ID,
		arg.UserID,
		arg.ProviderOrderCode,
		arg.CoinPackageID,
		arg.AmountVnd,
		arg.XuAmount,
		arg.CheckoutUrl,
	)
	return err
}

const getPaymentOrder = `-- name: GetPaymentOrder :one
SELECT id, provider, provider_order_code, coin_package_id, amount_vnd, xu_amount, status, checkout_url, created_at, paid_at
FROM payment_orders
WHERE id = $1
LIMIT 1
`

type GetPaymentOrderRow struct {
	ID                pgtype.UUID
	Provider          string
	ProviderOrderCode string
	CoinPackageID     pgtype.UUID
	AmountVnd         int32
	XuAmount          int32
	Status            string
	CheckoutUrl       *string
	CreatedAt         pgtype.Timestamptz
	PaidAt            pgtype.Timestamptz
}

func (q *Queries) GetPaymentOrder(ctx context.Context, db DBTX, id pgtype.UUID) (GetPaymentOrderRow, error) {
	row := db.QueryRow(ctx, getPaymentOrder, id)
	var i GetPaymentOrderRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderOrderCode,
		&i.CoinPackageID,
		&i.AmountVnd,
		&i.XuAmount,
		&i.Status,
		&i.CheckoutUrl,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const lockPaymentOrder = `-- name: LockPaymentOrder :one
SELECT id, status, xu_amount, user_id, coin_package_id
FROM payment_orders
WHERE provider_order_code = $1
FOR UPDATE
`

type LockPaymentOrderRow struct {
	ID            pgtype.UUID
	Status        string
	XuAmount      int32
	UserID        pgtype.UUID
	CoinPackageID pgtype.UUID
}

func (q *Queries) LockPaymentOrder(ctx context.Context, db DBTX, providerOrderCode string) (LockPaymentOrderRow, error) {
	row := db.QueryRow(ctx, lockPaymentOrder, providerOrderCode)
	var i LockPaymentOrderRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.XuAmount,
		&i.UserID,
		&i.CoinPackageID,
	)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE payment_orders
SET status = 'paid', paid_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkOrderPaid(ctx context.Context, db DBTX, id pgtype.UUID) error {
	_, err := db.Exec(ctx, markOrderPaid, id)
	return err
}
