// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendLedger = `-- name: AppendLedger :exec
INSERT INTO wallet_ledger
  (user_id, kind, available_delta_xu, held_delta_xu,
   balance_available_after, balance_held_after,
   reference_type, reference_id, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AppendLedgerParams struct {
	UserID                pgtype.UUID
	Kind                  string
	AvailableDeltaXu      int32
	HeldDeltaXu           int32
	BalanceAvailableAfter int32
	BalanceHeldAfter      int32
	ReferenceType         string
	ReferenceID           string
	Note                  *string
}

func (q *Queries) AppendLedger(ctx context.Context, db DBTX, arg *AppendLedgerParams) error {
	_, err := db.Exec(ctx, appendLedger,
		arg.UserID,
		arg.Kind,
		arg.AvailableDeltaXu,
		arg.HeldDeltaXu,
		arg.BalanceAvailableAfter,
		arg.BalanceHeldAfter,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Note,
	)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, available_xu, held_xu
FROM wallet_accounts
WHERE user_id = $1
LIMIT 1
`

type GetWalletRow struct {
	UserID      pgtype.UUID
	AvailableXu int32
	HeldXu      int32
}

func (q *Queries) GetWallet(ctx context.Context, db DBTX, userID pgtype.UUID) (GetWalletRow, error) {
	row := db.QueryRow(ctx, getWallet, userID)
	var i GetWalletRow
	err := row.Scan(&i.UserID, &i.AvailableXu, &i.HeldXu)
	return i, err
}

const listLedger = `-- name: ListLedger :many
SELECT id, kind, available_delta_xu, held_delta_xu, reference_type, reference_id, note, created_at
FROM wallet_ledger
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListLedgerParams struct {
	UserID pgtype.UUID
	Limit  int32
}

type ListLedgerRow struct {
	ID               pgtype.UUID
	Kind             string
	AvailableDeltaXu int32
	HeldDeltaXu      int32
	ReferenceType    string
	ReferenceID      string
	Note             *string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListLedger(ctx context.Context, db DBTX, arg *ListLedgerParams) ([]ListLedgerRow, error) {
	rows, err := db.Query(ctx, listLedger, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerRow
	for rows.Next() {
		var i ListLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AvailableDeltaXu,
			&i.HeldDeltaXu,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWallet = `-- name: LockWallet :one
SELECT user_id, available_xu, held_xu
FROM wallet_accounts
WHERE user_id = $1
FOR UPDATE
`

type LockWalletRow struct {
	UserID      pgtype.UUID
	AvailableXu int32
	HeldXu      int32
}

func (q *Queries) LockWallet(ctx context.Context, db DBTX, userID pgtype.UUID) (LockWalletRow, error) {
	row := db.QueryRow(ctx, lockWallet, userID)
	var i LockWalletRow
	err := row.Scan(&i.UserID, &i.AvailableXu, &i.HeldXu)
	return i, err
}

const updateWallet = `-- name: UpdateWallet :exec
UPDATE wallet_accounts
SET available_xu = $2, held_xu = $3, updated_at = now()
WHERE user_id = $1
`

type UpdateWalletParams struct {
	UserID      pgtype.UUID
	AvailableXu int32
	HeldXu      int32
}

func (q *Queries) UpdateWallet(ctx context.Context, db DBTX, arg *UpdateWalletParams) error {
	_, err := db.Exec(ctx, updateWallet, arg.UserID, arg.AvailableXu, arg.HeldXu)
	return err
}
