/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorkIdRouteImport } from './routes/w.$workId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminOpsRouteImport } from './routes/admin.ops'
import { Route as RWorkIdNumberNormRouteImport } from './routes/r.$workId.$numberNorm'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkIdRoute = WWorkIdRouteImport.update({
  id: '/w/$workId',
  path: '/w/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/admin/ops',
  path: '/admin/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const RWorkIdNumberNormRoute = RWorkIdNumberNormRouteImport.update({
  id: '/r/$workId/$numberNorm',
  path: '/r/$workId/$numberNorm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/w/$workId': typeof WWorkIdRoute
  '/r/$workId/$numberNorm': typeof RWorkIdNumberNormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/w/$workId': typeof WWorkIdRoute
  '/r/$workId/$numberNorm': typeof RWorkIdNumberNormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/ops': typeof AdminOpsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/w/$workId': typeof WWorkIdRoute
  '/r/$workId/$numberNorm': typeof RWorkIdNumberNormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/library'
    | '/login'
    | '/settings'
    | '/admin/ops'
    | '/auth/callback'
    | '/w/$workId'
    | '/r/$workId/$numberNorm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/library'
    | '/login'
    | '/settings'
    | '/admin/ops'
    | '/auth/callback'
    | '/w/$workId'
    | '/r/$workId/$numberNorm'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/library'
    | '/login'
    | '/settings'
    | '/admin/ops'
    | '/auth/callback'
    | '/w/$workId'
    | '/r/$workId/$numberNorm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  WWorkIdRoute: typeof WWorkIdRoute
  RWorkIdNumberNormRoute: typeof RWorkIdNumberNormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workId': {
      id: '/w/$workId'
      path: '/w/$workId'
      fullPath: '/w/$workId'
      preLoaderRoute: typeof WWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/admin/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$workId/$numberNorm': {
      id: '/r/$workId/$numberNorm'
      path: '/r/$workId/$numberNorm'
      fullPath: '/r/$workId/$numberNorm'
      preLoaderRoute: typeof RWorkIdNumberNormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AdminOpsRoute: AdminOpsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  WWorkIdRoute: WWorkIdRoute,
  RWorkIdNumberNormRoute: RWorkIdNumberNormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
