"""Store — protocol for chapter translation storage operations."""

from __future__ import annotations

from typing import Protocol


class Store(Protocol):
    """Storage interface — translate pipeline + API operations."""

    # ── Translate pipeline ────────────────────────────────────────
    async def get_glossary(self, project_id: int) -> dict[str, str]: ...
    async def list_glossary(self, project_id: int) -> list[dict]: ...
    async def upsert_glossary_term(
        self, project_id: int, source_term: str, target_term: str,
        notes: str | None = None,
    ) -> int: ...
    async def delete_glossary_term(self, project_id: int, term_id: int) -> bool: ...
    async def glossary_search(self, project_id: int, query: str) -> list[dict]: ...
    async def save_chapter_brief(self, chapter_id: int, brief: dict) -> None: ...
    async def get_chapter_brief(self, chapter_id: int) -> dict | None: ...
    async def get_recent_chapter_briefs(
        self, project_id: int, before_chapter_idx: float, limit: int = 3
    ) -> list[dict]: ...
    async def search_briefs(
        self, project_id: int, queries: list[str], limit: int = 10,
        *, before_chapter_idx: float | None = None
    ) -> list[str]: ...
    async def search_context(
        self, project_id: int, queries: list[str], scope: str = "all", limit: int = 12
    ) -> list[str]: ...
    async def save_translations(self, chapter_id: int, records: list[dict]) -> None: ...
    async def update_translation(
        self, chapter_id: int, page_index: int, bubble_idx: int,
        translated_text: str, kind: str | None = None,
    ) -> bool: ...
    async def save_bubbles(self, chapter_id: int, bubbles: list[dict]) -> None: ...
    async def get_bubbles(self, chapter_id: int) -> list[dict]: ...
    async def save_geometry(self, chapter_id: int, pages: list[dict]) -> None: ...
    async def get_geometry(self, chapter_id: int) -> list[dict]: ...
    async def get_translations(self, chapter_id: int) -> dict[tuple[int, int], dict]: ...

    # ── API operations ────────────────────────────────────────────
    async def list_projects(self) -> list[dict]: ...
    async def get_project(self, project_id: int) -> dict | None: ...
    async def get_project_by_slug(self, slug: str) -> dict | None: ...
    async def get_or_create_project(
        self, slug: str, title: str, source_lang: str, target_lang: str,
        source_url: str | None = None,
    ) -> int: ...
    async def update_project_metadata(
        self, project_id: int, *,
        title: str | None = None,
        description: str | None = None,
        cover_path: str | None = None,
        target_lang: str | None = None,
        settings: dict | None = None,
    ) -> None: ...
    async def get_project_settings(self, project_id: int) -> dict: ...
    async def get_all_chapters(self, project_id: int) -> list[dict]: ...
    async def get_chapters_with_status(self, project_id: int) -> list[dict]: ...
    async def get_chapter_with_status(self, chapter_id: int, project_id: int) -> dict | None: ...
    async def get_chapter(self, chapter_id: int) -> dict | None: ...
    async def get_tasks(self, chapter_id: int) -> list[dict]: ...
    async def enqueue(self, chapter_id: int, stage: str) -> None: ...
    async def delete_chapter_data(self, chapter_id: int) -> None: ...
    async def delete_chapter(self, chapter_id: int) -> bool: ...
    async def get_or_create_chapter(
        self, project_id: int, idx: float,
        source_url: str | None = None,
        title: str | None = None,
    ) -> int: ...
    async def delete_project(self, project_id: int) -> None: ...
    async def get_chapter_progress(self, chapter_id: int) -> dict | None: ...
    async def queue_stats(self) -> dict: ...

    # ── Chapter archive state ─────────────────────────────────────
    async def set_prepared_done(self, chapter_id: int, page_count: int) -> None:
        """Mark a chapter as prepared and reset `rendered` to false."""
        ...

    async def set_rendered(self, chapter_id: int, rendered: bool) -> None:
        """Flip the persistent `rendered` flag. The tasks table is the only
        source of truth for render-in-flight; render concurrency comes from
        `claim_task('render', ...)`."""
        ...

    async def get_chapter_render_state(self, chapter_id: int) -> dict | None:
        """Return {rendered: bool, page_count: int} or None if missing."""
        ...
