"""Store — protocol for chapter translation storage operations."""

from __future__ import annotations

from typing import Protocol


class Store(Protocol):
    """Storage interface — translate pipeline + API operations."""

    # ── Translate pipeline ────────────────────────────────────────
    async def get_glossary(self, project_id: int) -> dict[str, str]: ...
    async def glossary_search(self, project_id: int, query: str) -> list[dict]: ...
    async def save_chapter_brief(self, chapter_id: int, brief: dict) -> None: ...
    async def get_recent_chapter_briefs(
        self, project_id: int, before_chapter_idx: float, limit: int = 3
    ) -> list[dict]: ...
    async def search_briefs(
        self, project_id: int, queries: list[str], limit: int = 10,
        *, before_chapter_idx: float | None = None
    ) -> list[str]: ...
    async def search_context(
        self, project_id: int, queries: list[str], scope: str = "all", limit: int = 12
    ) -> list[str]: ...
    async def save_translations(self, chapter_id: int, records: list[dict]) -> None: ...
    async def save_bubbles(self, chapter_id: int, bubbles: list[dict]) -> None: ...
    async def get_bubbles(self, chapter_id: int) -> list[dict]: ...
    async def get_translations(self, chapter_id: int) -> dict[tuple[int, int], dict]: ...

    # ── API operations ────────────────────────────────────────────
    async def list_projects(self) -> list[dict]: ...
    async def get_project(self, project_id: int) -> dict | None: ...
    async def get_project_by_slug(self, slug: str) -> dict | None: ...
    async def get_or_create_project(
        self, slug: str, title: str, source_lang: str, target_lang: str,
        source_url: str | None = None,
    ) -> int: ...
    async def get_all_chapters(self, project_id: int) -> list[dict]: ...
    async def get_chapters_with_status(self, project_id: int, projects_root, slug: str) -> list[dict]: ...
    async def get_chapter_with_status(self, chapter_id: int, project_id: int, projects_root, slug: str) -> dict | None: ...
    async def get_chapter(self, chapter_id: int) -> dict | None: ...
    async def get_tasks(self, chapter_id: int) -> list[dict]: ...
    async def enqueue(self, chapter_id: int, stage: str) -> None: ...
    async def delete_chapter_data(self, chapter_id: int) -> None: ...
    async def get_or_create_chapter(
        self, project_id: int, idx: float, source_url: str | None = None,
    ) -> int: ...
    async def delete_project(self, project_id: int) -> None: ...
    async def get_chapter_progress(self, chapter_id: int) -> dict | None: ...

    # ── Bunle artifact pointers ───────────────────────────────────
    async def set_prepared_artifact(
        self, chapter_id: int, *, prepared_key: str, page_count: int,
    ) -> str | None:
        """Atomically swap prepared_key. Returns the previous key (may be None)
        so the caller can delete the old object after the pointer flip.
        Resets render state to 'none' and clears render_key/render_job_id."""
        ...

    async def claim_render_job(self, chapter_id: int, job_id: str) -> bool:
        """CAS: transition render_state -> 'rendering' iff not already rendering.
        Returns True if claim succeeded (this worker holds the job)."""
        ...

    async def finish_render_artifact(
        self, chapter_id: int, *, job_id: str, render_key: str,
    ) -> tuple[bool, str | None]:
        """CAS finish: set render_key + render_state='rendered' iff job_id matches.
        Returns (won, previous_render_key) — won=False if another job took over."""
        ...

    async def fail_render_job(self, chapter_id: int, job_id: str, error: str) -> None:
        """Mark current render attempt as failed. render_key is left intact."""
        ...

    async def mark_render_stale(self, chapter_id: int) -> None:
        """Move render_state to 'stale' if a render_key already exists."""
        ...

    async def get_chapter_artifacts(self, chapter_id: int) -> dict | None:
        """Return prepared_key/render_key/render_state/page_count or None."""
        ...
